### ISSUE TITLE
Impossible to start .exe + What .dat files and .exe files should i use to create Aspect's .txt readable files?

### ISSUE THREAD

**Issue by Francyrad** [jadconnolly/Perple_X#2]
Dear developers

I would like to use the program to create eos tabs to use on ASPECT. But I encountered two problems:

I have downloaded the version For Apple’s ARM processors, and the.exe files work, however I am not able to read the.dat files provided in the examples despite these being in the same folder. I'm I doing something wrong?

Thank you for the availability
Francesco

**Comment by boriskaus** [comment]
can you give us a minimum working example (MWE), so that we can reproduce this?

**Comment by Francyrad** [comment]
I downloaded this version:
```
Perple_X_7.0.9_OSX_ARM_SP_Apr_16_2023
```
Then i ran that .exe:  dynamic/actcor.exe:
```
/Users/francyrad/Downloads/Perple_X_7.0.9_OSX_ARM_SP_Apr_16_2023/dynamic/actcor ; exit;
/Users/francyrad/.zshrc:31: permission denied: /Users/francyrad/Documents/PyFrac
francyrad@MacBook-Pro-di-Francesco ~ % /Users/francyrad/Downloads/Perple_X_7.0.9_OSX_ARM_SP_Apr_16_2023/dynamic/actcor ; exit;

Perple_X release 7.0.9, March 27, 2023.

Copyright (C) 1986-2023 James A D Connolly <www.perplex.ethz.ch/copyright.html>.

NO is the default answer to all prompts


Enter thermodynamic data file name [default = hp02ver.dat]:


**warning ver191** FOPEN2 cannot find file:
hp02ver.dat                                                                                         

try again (y/n)?
y

Enter thermodynamic data file name [default = hp02ver.dat]:
y

**warning ver191** FOPEN2 cannot find file:
y                                                                                                   

try again (y/n)?
y

Enter thermodynamic data file name [default = hp02ver.dat]:
y

**warning ver191** FOPEN2 cannot find file:
y                                                                                                   

try again (y/n)?


O.K., I quit too.

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

The file `hp02ver.dat` is in the folder and it's been taken from PerpleX 6.9.1 data files.
Is this given by the fact that i'm using data from previous version? I didn't find 7.0.1 data in the website.

Thank you for the availability

**Comment by boriskaus** [comment]
it's not clear to me whether you are running this from the terminal or whether you run this through Julia, or whether you compiled this yourself or are relying on precompiled binaries. If you downloaded the precompiled version of Perple_X, and run it from the terminal you will need to link all required dynamic libraries. Julia will take care of that.

**Comment by Francyrad** [comment]
Thank you for the suggestion. I've been able to run my script using Julia at the end, but i had to put all my .dat files in my HOME to make it works. Is there a way to put them in a desired folder instead of HOME so that PerpleX can find them? like specifying a path?

Thank you for your help and availability
